### ISSUE TITLE
Dataset?

### ISSUE THREAD

**Issue by ghost** [orange-fritters/fastMRI#1]
Hi @orange-fritters , 
Thank you for the public code. I learned a lot from your skills.
So, could you please share the dataset in order for me to learn and test the performance of the network?
It would be really great!!! 

Thank you, 
Tin

**Comment by orange-fritters** [comment]
Hey @ngthanhtin,
Thank you for having an interest in my work.
You can find and get access to the dataset here https://fastmri.med.nyu.edu/

**Comment by ghost** [comment]
Thank you very much!!! @orange-fritters
